function res = sddma(root_dir, modelfile, output_dir, display)
%SDDMA implements the adaptive skin detection process based on maximization 
% of mutual information. First, the optimum colour channels are selected among 
% HSV, RGV, YCbCr and LAB, to compose two detectors. Each detector thresholds 
% the two channels within an agreement maximization framework. Finally, both 
% detectors are combined using mathematical morphology as described in:
%   Juan C. SanMiguel & Sergio Suja, "Skin detection by dual maximization
%   of detectors agreement for video monitoring", Pattern Recognition Letters, 2013
%
% Input:
%   - root_dir: root directory with the dataset to process (annotated and raw images, 
%       respectively in subdirs 'ann' and 'raw'). Skin annotations are indicated in 
%       pure red colour for each pixel([255 0 0]). All N test images must be in PNG format.
%   - modelfile: path to the mat file containing the trained models (analysis of the optimum color spaces)
%   - output_dir: directory to save image and mat data of SDDMA.
%   - display: 0-no display 1-visual display 
%
% Output: 
%   - res: the generated results as struct variable for each tested image (1...N). 
%          The fields of the struct are:
%         * 'type'- channels combined
%         * 'tp' - Nx1 vector with true positives for each image
%         * 'fp' - Nx1 vector with false positives for each image 
%         * 'fn' - Nx1 vector with false negatives for each image 
%         * 'P'  - Nx1 vector with Precision results for each image
%         * 'mP' - 1x1 vector with mean Precision results
%         * 'R'  - Nx1 vector with Recall results for each image 
%         * 'mR' - 1x1 vector with mean Recall results
%         * 'F'  - Nx1 vector with F-score results for each image 
%         * 'mF' - 1x1 vector with mean F-score results
%         * 'A'  - Nx1 vector with Agreement results between the two detectors for each frame
%         * 'total_pix' - Total number of pixels analyzed 
%         * 'total_skin_pix' - Total number of skin pixels analyzed 
%         * 'Nima' - Total number of images analyzed (N)
%         * 'skinres' - Additional data generated by the SDDMA algorithm
%
% Author:   Juan C. San Miguel & Sergio Surja (VPU-Lab)
% E-mail:   juancarlos.sanmiguel@uam.es
% URL:      http://www-vpu.eps.uam.es/~jcs
% Version & date: 1.0 (Sept 2013)
%
% Modification/redistribution granted only for the purposes of teaching, non-commercial research or study.